

<div class="row">
          <?php foreach ($entries as $entry) { ?>
          <div class="entry">
            <div class="entry-container">
              <div class="entry-title">
                  
                  <div class="entry-header">
                  <h2 class="entry-title"><a href="<?=$this->url('entry', array('id' => $entry['idEntry'],'slug' => $entry['slug'] )); ?>"><?=$entry['title']; ?></a></h2> 
                </div>
                <div class="entry-summary" ><?=$entry['text']; ?></div>
              </div>
            </div>
            <div class="entry-meta">
              <span class="entry-num-comments">
                <a href="<?=$this->url('entry', array('id' => $entry['idEntry'],'slug' => $entry['slug'] )); ?>#disqus_thread">0 comentarios</a>
              </span>
              <span class="entry-date">
                <a href=""><?=$entry['postedAt']->format('d/m/Y'); ?></a>
              </span>
            </div>
          </div>
          <? } ?>
</div>

<? if(!(count($entries)>1)){ ?>
 <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'tineo'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<? } ?>