<div class="inner-menu nav-collapse ">   
      <div class="inner-wrapper" >    
    <a href="<?=$this->url('dashboard',array('controller'=>'entry')); ?>/#new" class="btn btn-block btn-primary" ><span class="bold">CREAR</span></a>
    
   </div>
   <div class="inner-menu-content">
    <p class="menu-title">Entradas <span class="pull-right"><i class="icon-refresh"></i></span></p>
    </div>
   <ul class="big-items">
    <!-- <li class="active"><span class="badge badge-important">2</span><a href="<?=$this->url('dashboard',array('controller'=>'entry')); ?>/#inbox" > Inbox</a></li> -->
    <li><a href="<?=$this->url('dashboard',array('controller'=>'entry', "action" => 'view')); ?>" >Publicados</a></li>
    <li><a href="<?=$this->url('dashboard',array('controller'=>'entry', "action" => 'view')); ?>" >Borradores</a></li>
    <li><a href="<?=$this->url('dashboard',array('controller'=>'entry', "action" => 'view')); ?>" >Papelera</a></li>
   </ul>
  <!-- <ul class="small-items">
    <li class=""><a href="#" > Home</a></li>
    <li><span class="badge badge-important">2</span><a href="#"> Work</a></li>
   </ul>
  <div class="inner-wrapper" >            
    <p class="menu-title">QUICK VIEW</p>    
   </div>
  <ul class="small-items">
    <li class=""><a href="#"> Documents</a></li>
    <li class=""><span class=" badge badge-disable ">203</span><a href="#"> Images</a></li>
    <li class=""><a href="#"> Flagged</a></li>    
  </ul> -->
</div> 