<!DOCTYPE html>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<meta charset="utf-8" />
<title>Makiblog - Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="" name="description" />
<meta content="" name="author" />
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))

    ->prependStylesheet($this->basePath() .'/assets/css/custom-icon-set.css')
    ->prependStylesheet($this->basePath() .'/assets/css/style.css')

    ->prependStylesheet($this->basePath() .'/assets/css/animate.min.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/font-awesome/css/font-awesome.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/bootstrap/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/bootstrap/css/bootstrap.min.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/pace/pace-theme-flash.css');
?>

<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    
    ->prependFile($this->basePath() . '/assets/js/login.js')
    ->prependFile($this->basePath() . '/assets/plugins/jquery-validation/js/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/jquery-1.8.3.min.js');
?>

</head>
<body class="error-body no-top">
<div class="container">
  <div class="row">
    <div class="login-container span12">
      <div class="row-fluid column-seperation" style="padding:0 10px">
        <div class="span6 offset1">
          <h2>Ingresa al Blog</h2>
          <p>Usa tu cuenta de Facebook, Twitter o usuario para autenticarte.<br>
            <?php if ($this->enableRegistration) : ?>
            <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up Now!</a> for a Makiblog account,It's free and always will be..</p>
            <?php endif; ?>
          <br>
          <div class="row-fluid">
            <button class="btn btn-block btn-info span10" type="button">
            <div class="pull-left"><i class="icon-facebook"></i></div>
            <span class="bold">Login with Facebook</span> </button>
          </div>
          <br>
          <div class="row-fluid">
            <button class="btn btn-block btn-success span10" type="button">
            <div class="pull-left"><i class="icon-twitter"></i></div>
            <span class="bold">Login with Twitter</span></button>
          </div>
        </div>
        <div class="span5"> <br>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

<?php echo $this->formElementErrors($form->get('identity')) ?>
<div class="row-fluid">
     <div class="control-group span10">
            <label class="control-label"><?php echo $this->formLabel($form->get('identity')) ?></label>
            <div class="controls">
        <div class="input-with-icon  right">                                       
          <i class=""></i>
          <?php echo $this->formInput($form->get('identity')->setAttribute('class','span12')) ?></div>
            </div>
          </div>
          </div>
      <div class="row-fluid">
          <div class="control-group span10">
            <label class="control-label"><?php echo $this->formLabel($form->get('credential')) ?></label>
            <span class="help"></span>
            <div class="controls">
        <div class="input-with-icon  right">                                       
          <i class=""></i>
          <?php echo $this->formInput($form->get('credential')->setAttribute('class','span12')) ?></div>
            </div>
          </div>
          </div>
      <div class="row-fluid">
          <div class="control-group  span10">
            <div class="checkbox checkbox check-success"> <a href="#">¿ Olvidaste la contraseña?</a>&nbsp;&nbsp;
              <input type="checkbox" id="checkbox1" value="1">
              <label for="checkbox1">Recordarme </label>
            </div>
          </div>
          </div>
          

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <div class="row-fluid">
            <div class="span10"><?php echo $this->formButton($form->get('submit')->setAttribute('class','btn btn-primary btn-cons pull-right')) ?></div>
        </div>

<?php echo $this->form()->closeTag() ?>

      </div>
    </div>
  </div>
</div>


</body>
</html>