<article class="post-167 post type-post status-publish format-quote hentry category-celebs tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry entry-quote">  
        <p>&#8220;Give a girl the right shoes, and she can conquer the world.&#8221;</p>
    <div class="entry-quote-author">- Marilyn Monroe -</div>
    </article><!-- /loop-entry -->

 
<article class="post-102 post type-post status-publish format-audio hentry category-celebs tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">
                <a href="index.html%3Fp=102.html" title="Get Her New Song" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/rockers-girlfriend-440x342.jpg" alt="Get Her New Song" />
            <div class="entry-overlay"><span class="icon-music"></span></div>
        </a>
        
    
        
        <h2 class="loop-entry-title-margin"><a href="index.html%3Fp=102.html" title="Get Her New Song">Get Her New Song</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=102.html#comments" class="comments-link"  title="Comment on Get Her New Song">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-102" title="Like this"><span class="zilla-likes-count">204</span> <span class="zilla-likes-postfix"></span></a></li>         </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /loop-entry -->

 
<article class="post-106 post type-post status-publish format-image hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
                <a href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zphotodune-1303204-fashion-woman-m.jpg" title="Bold Outerwear" class="loop-entry-img-link fancybox">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zphotodune-1303204-fashion-woman-m-440x440.jpg" alt="Bold Outerwear" />
            <div class="entry-overlay"><span class="icon-fullscreen"></span></div>
        </a>
            <h2><a href="index.html%3Fp=106.html" title="Bold Outerwear">Bold Outerwear</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=106.html#comments" class="comments-link"  title="Comment on Bold Outerwear">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-106" title="Like this"><span class="zilla-likes-count">118</span> <span class="zilla-likes-postfix"></span></a></li>         </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->
 
<article class="post-115 post type-post status-publish format-gallery hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry grid-4 container clearfix">  
                <a href="index.html%3Fp=115.html" title="Hot Accessory: Scarves" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zphotodune-2857325-fashionable-woman-with-sunglasses-m-440x537.jpg" alt="Hot Accessory: Scarves" />
            <div class="entry-overlay"><span class="icon-picture"></span></div>
        </a>
            <h2><a href="index.html%3Fp=115.html" title="Hot Accessory: Scarves">Hot Accessory: Scarves</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=115.html#comments" class="comments-link"  title="Comment on Hot Accessory: Scarves">4 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-115" title="Like this"><span class="zilla-likes-count">68</span> <span class="zilla-likes-postfix"></span></a></li>          </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-135 post type-post status-publish format-link hentry category-beauty tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
                <h2><a href="http://themeforest.net/user/WPExplorer" title="15% Off Lip Gloss" target="_blank">15% Off Lip Gloss</a></h2>
        <div class="entry-text">
            <p>Vestibulum ultrices adipiscing turpis quis feugiat. Cras sed mauris nec diam aliquet ultrices vitae sit</p>
<p><em><strong>AMET JUSTO</strong></em></p>
             <ul class="loop-entry-meta clearfix">
                <li><span class="icon-link"></span><a href="http://themeforest.net/user/WPExplorer" title="15% Off Lip Gloss" target="_blank">http://themeforest.net/user/WPExplorer</a></li>    
           </ul> 
        </div><!-- /entry-text -->
    </article><!-- /entry -->
 
<article class="post-96 post type-post status-publish format-standard hentry category-love tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
            <a href="index.html%3Fp=96.html" title="Moving in Together" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/photodune-2361374-new-home-m-440x432.jpg" alt="Moving in Together" />
            <div class="entry-overlay"><span class="icon-plus"></span></div>
        </a>
            <h2><a href="index.html%3Fp=96.html" title="Moving in Together">Moving in Together</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=96.html#comments" class="comments-link"  title="Comment on Moving in Together">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-96" title="Like this"><span class="zilla-likes-count">43</span> <span class="zilla-likes-postfix"></span></a></li>           </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-33 post type-post status-publish format-standard hentry category-celebs tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
            <a href="index.html%3Fp=33.html" title="Interview with a Rockstar" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/photodune-1405937-young-girl-with-a-guitar-m-440x659.jpg" alt="Interview with a Rockstar" />
            <div class="entry-overlay"><span class="icon-plus"></span></div>
        </a>
            <h2><a href="index.html%3Fp=33.html" title="Interview with a Rockstar">Interview with a Rockstar</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non? Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=33.html#comments" class="comments-link"  title="Comment on Interview with a Rockstar">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-33" title="Like this"><span class="zilla-likes-count">36</span> <span class="zilla-likes-postfix"></span></a></li>           </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-164 post type-post status-publish format-image hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
                <a href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zblack-and-white.jpg" title="Keep It Simple With Black &amp; White" class="loop-entry-img-link fancybox">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zblack-and-white-440x537.jpg" alt="Keep It Simple With Black &amp; White" />
            <div class="entry-overlay"><span class="icon-fullscreen"></span></div>
        </a>
            <h2><a href="index.html%3Fp=164.html" title="Keep It Simple With Black &amp; White">Keep It Simple With Black &amp; White</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=164.html#comments" class="comments-link"  title="Comment on Keep It Simple With Black &amp; White">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-164" title="Like this"><span class="zilla-likes-count">37</span> <span class="zilla-likes-postfix"></span></a></li>          </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->
 
<article class="post-22 post type-post status-publish format-gallery hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry grid-4 container clearfix">  
                <a href="index.html%3Fp=22.html" title="Hot Fall Trends!" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/photodune-2271303-pure-sexy-m-440x292.jpg" alt="Hot Fall Trends!" />
            <div class="entry-overlay"><span class="icon-picture"></span></div>
        </a>
            <h2><a href="index.html%3Fp=22.html" title="Hot Fall Trends!">Hot Fall Trends!</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=22.html#comments" class="comments-link"  title="Comment on Hot Fall Trends!">4 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-22" title="Like this"><span class="zilla-likes-count">20</span> <span class="zilla-likes-postfix"></span></a></li>           </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-148 post type-post status-publish format-standard hentry category-beauty tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos tag-products tag-reviews loop-entry container">  
            <a href="index.html%3Fp=148.html" title="Try These Hair Products Now" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zphotodune-3007452-luxory-brownhaired-model-m-440x293.jpg" alt="Try These Hair Products Now" />
            <div class="entry-overlay"><span class="icon-plus"></span></div>
        </a>
            <h2><a href="index.html%3Fp=148.html" title="Try These Hair Products Now">Try These Hair Products Now</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="index.html%3Fp=148.html#comments" class="comments-link"  title="Comment on Try These Hair Products Now">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-148" title="Like this"><span class="zilla-likes-count">15</span> <span class="zilla-likes-postfix"></span></a></li>          </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->