<!DOCTYPE html>

<html lang="en-US">
<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
        <!-- Mobile Specific -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
        <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
        
    <!-- Title Tag -->
	<title>Fashionista </title>
    
           
    <!-- Browser dependent stylesheets -->
    <!--[if IE 8]>
        <link rel="stylesheet" type="text/css" href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/themes/fashionista/css/ie8.css" media="screen" />
    <![endif]-->
    
    <!--[if IE 7]>
        <link rel="stylesheet" type="text/css" href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/themes/fashionista/css/ie7.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/themes/fashionista/css/font-awesome-ie7.min.css" media="screen" />
    <![endif]-->
    
    <!-- Load HTML5 dependancies for IE -->
    <!--[if IE]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    
    <!-- WP Head -->
    <link rel="alternate" type="application/rss+xml" title="Fashionista &raquo; Feed" href="feed/index.html" />
<link rel="alternate" type="application/rss+xml" title="Fashionista &raquo; Comments Feed" href="comments/feed/index.html" />
<link rel='stylesheet' id='contact-form-7-css'  href='css/styles.css' type='text/css' media='all' />
<link rel='stylesheet' id='zilla-likes-css'  href='css/zilla-likes.css' type='text/css' media='all' />
<link rel='stylesheet' id='wpex-style-css'  href='css/style.css' type='text/css' media='all' />
<link rel='stylesheet' id='wpex-droid-serif-css'  href='http://fonts.googleapis.com/css?family=Droid+Serif%3A400%2C400italic' type='text/css' media='all' />
<link rel='stylesheet' id='wpex-open-sans-css'  href='http://fonts.googleapis.com/css?family=Open+Sans%3A400italic%2C600italic%2C700italic%2C400%2C600%2C700&#038;subset=latin%2Ccyrillic-ext%2Clatin-ext%2Ccyrillic%2Cgreek-ext%2Cgreek%2Cvietnamese' type='text/css' media='all' />
<link rel='stylesheet' id='responsive-css'  href='css/responsive.css' type='text/css' media='all' />
<script type='text/javascript' src='js/jquery.js'></script>
<script type='text/javascript' src='js/jquery-migrate.min.js'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var zilla = {"ajaxurl":"http:\/\/wpexplorer-demos.com\/fashionista\/wp-admin\/admin-ajax.php"};
var zilla_likes = {"ajaxurl":"http:\/\/wpexplorer-demos.com\/fashionista\/wp-admin\/admin-ajax.php"};
/* ]]> */
</script>
<script type='text/javascript' src='js/zilla-likes.js'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="xmlrpc.php%3Frsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="wp-includes/wlwmanifest.xml" /> 
    
    </head><!-- /end head -->

<!-- Begin Body -->

<body class="home blog body ">

<div id="header-wrap">
    <header id="header" class="outerbox clearfix">
        	<div id="header-top">
            <div id="logo" class="clearfix">
                <a href="/" title="Fashionista" rel="home">
                                            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2013/11/logo.png" alt="" />
                                    </a>
            </div><!-- /logo -->
                        <ul id="header-social">
                <li><a href="http://www.twitter.com/wpexplorer" title="twitter" target="_blank" class="wpex-tooltip"><img src="images/social/twitter.png" alt="twitter" /></a></li>
                <li><a href="http://www.facebook.com/WPExplorerThemes" title="facebook" target="_blank" class="wpex-tooltip"><img src="images/social/facebook.png" alt="facebook" /></a></li>
                <li><a href="https://plus.google.com/114591575651122645032/posts" title="googleplus" target="_blank" class="wpex-tooltip"><img src="images/social/googleplus.png" alt="googleplus" /></a></li>
                <li><a href="http://www.flickr.com/photos/we-are-envato/" title="flickr" target="_blank" class="wpex-tooltip"><img src="images/social/flickr.png" alt="flickr" /></a></li>
                <li><a href="http://dribbble.com/aj-clarke" title="dribbble" target="_blank" class="wpex-tooltip"><img src="images/social/dribbble.png" alt="dribbble" /></a></li>
                <li><a href="http://tumblr.com" title="tumblr" target="_blank" class="wpex-tooltip"><img src="images/social/tumblr.png" alt="tumblr" /></a></li>
                <li><a href="http://www.wpexplorer.me/premium/fashionista/rss" title="rss" target="_blank" class="wpex-tooltip"><img src="images/social/rss.png" alt="rss" /></a></li>
                <li><a href="/" title="mail" target="_blank" class="wpex-tooltip"><img src="images/social/mail.png" alt="mail" /></a></li>                </ul><!-- /header-social -->
                    </div><!-- /header-top -->
		<div id="sidr-close"><a href="index.html#sidr-close" class="toggle-sidr-close"></a></div><a href="index.html#sidr" class="mobile-menu-toggle"><span class="icon-reorder"></span>Browse<span class="icon-caret-down"></span></a>		<nav id="navigation" class="clearfix">
			<div class="menu-main-menu-container"><ul id="menu-main-menu" class="sf-menu"><li id="menu-item-332" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-332"><a href="/">Home</a></li>
<li id="menu-item-367" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-367"><a href="index.html%3Fp=353.html">Home &#038; Sidebar1</a></li>
<li id="menu-item-333" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-333"><a href="index.html#">Categories</a>
<ul class="sub-menu">
	<li id="menu-item-334" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-334"><a href="category/fashion/index.html">Fashion</a></li>
	<li id="menu-item-335" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-335"><a href="category/celebs/index.html">Celebs</a></li>
	<li id="menu-item-336" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-336"><a href="category/beauty/index.html">Beauty</a></li>
	<li id="menu-item-337" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-337"><a href="category/advice/index.html">Advice</a></li>
	<li id="menu-item-338" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-338"><a href="category/love/index.html">Love</a></li>
</ul>
</li>
<li id="menu-item-340" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-340"><a href="index.html#">Post Formats</a>
<ul class="sub-menu">
	<li id="menu-item-372" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-372"><a href="type/image/index.html">Image</a></li>
	<li id="menu-item-373" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-373"><a href="type/gallery/index.html">Gallery</a></li>
	<li id="menu-item-374" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-374"><a href="type/quote/index.html">Quote</a></li>
	<li id="menu-item-375" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-375"><a href="type/link/index.html">Link</a></li>
	<li id="menu-item-376" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-376"><a href="type/audio/index.html">Audio</a></li>
	<li id="menu-item-377" class="menu-item menu-item-type-taxonomy menu-item-object-post_format menu-item-377"><a href="type/video/index.html">Video</a></li>
</ul>
</li>
<li id="menu-item-369" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-369"><a href="index.html%3Fp=251.html">About Me</a></li>
<li id="menu-item-368" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-368"><a href="index.html%3Fp=241.html">Contact</a></li>
</ul></div>			<form method="get" id="searchbar" action="index.html">
<input type="search" name="s" id="search" value="Search..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
<input type="submit" id="searchsubmit" value="" />
</form>       </nav><!-- /navigation -->
       	</header><!-- /header -->
</div><!-- /header-wrap -->
    
<div id="wrap">

<div id="main-content" class="outerbox clearfix fitvids infinite-scroll-enabled">
  

	
    <div id="home-wrap" class="clearfix">
    	<div class="grid-loader"><i class="icon-spinner icon-spin"></i></div>
         <div id="wpex-grid-wrap">
           
        <?php echo $this->content; ?>

        </div><!-- /wpex-grid-wrap -->
                	<div class="infinite-scroll-nav clr"><div class="alignleft newer-posts"></div><div class="alignright older-posts"><a href="page/2/index.html" >Older Posts &rarr;</a></div></div>            </div><!-- /home-wrap -->
    
<div class="clear"></div>
</div><!-- /main-content -->
</div><!-- /wrap -->

<div id="footer-wrap">
		    <footer id="footer" class="outerbox">
        <div id="footer-widgets" class="clearfix">
            <div class="footer-box">
            	<div class="footer-widget widget_text clearfix"><h4>Fashionista</h4>			<div class="textwidget">Behold a Fashionista a super clean and elegant WordPress theme for fashion bloggers. This theme is perfect for sharing all sorts of media online. Photos, videos, quotes, links..etc.</div>
		</div>            </div>
            <!-- /footer-one -->
            <div class="footer-box">
            			<div class="footer-widget widget_recent_entries clearfix">		<h4>Recent Posts</h4>		<ul>
					<li>
				<a href="index.html%3Fp=167.html">Marilyn Monroe</a>
						</li>
					<li>
				<a href="index.html%3Fp=102.html">Get Her New Song</a>
						</li>
					<li>
				<a href="index.html%3Fp=106.html">Bold Outerwear</a>
						</li>
					<li>
				<a href="index.html%3Fp=115.html">Hot Accessory: Scarves</a>
						</li>
				</ul>
		</div>            </div>
            <!-- /footer-two -->
            <div class="footer-box remove-margin">
            	<div class="footer-widget flickr_widget clearfix"><h4>Flickr Feed</h4>		
				<div class="wpex-flickr-widget">
					<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=8&amp;display=latest&amp;size=s&amp;layout=x&amp;source=user&amp;user=52617155@N08"></script>
				</div>
			</div>            </div>
            <!-- /footer-three -->
        </div>
        <!-- /footer-widgets -->
    </footer>
    <!-- /footer -->
        <div id="footer-bottom">
    	<div class="outerbox clearfix">
            <div id="copyright">
                &copy; Copyright 2013            </div><!-- /copyright -->
            <ul id="menu-footer" class="footer-menu"><li id="menu-item-339" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-339"><a href="index.html">Home</a></li>
<li id="menu-item-370" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-370"><a href="index.html%3Fp=251.html">About Me</a></li>
<li id="menu-item-371" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-371"><a href="index.html%3Fp=241.html">Contact</a></li>
</ul>        </div><!-- /outerbox -->
	</div><!-- /footer-bottom -->
    </div><!-- /footer-wrap -->
<a href="index.html#toplink" id="toplink"><span class="icon-chevron-up"></span></a>


<script type='text/javascript' src='js/jquery.form.min.js'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/wpexplorer-demos.com\/fashionista\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ...","cached":"1"};
/* ]]> */
</script>
<script type='text/javascript' src='js/scripts.js'></script>
<script type='text/javascript' src='js/devicepx-jetpack.js'></script>
<script type='text/javascript' src='js/plugins.js'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var wpexvars = {"ajaxurl":"http:\/\/wpexplorer-demos.com\/fashionista\/wp-admin\/admin-ajax.php","loading":"loading...","loadmore":"load more"};
/* ]]> */
</script>
<script type='text/javascript' src='js/global.js'></script>
<script type='text/javascript' src='js/infinitescroll-init.js'></script>
    
</body>
</html>