<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Tineo') ) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style_tineo.css')
                        ->prependStylesheet($this->basePath() . '/css/sticky-footer-navbar.css')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Titillium+Web')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Play')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Economica')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>


        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
            <!-- Wrap all page content here -->
  <div id="wrap">
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?=$this->url('pages');?>">Tineo</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="<?=$this->url('pages');?>">Home</a></li>
              <li><a href="<?=$this->url('pages',array('page'=>'about'));?>">About</a></li>
              <li><a href="<?=$this->url('pages',array('page'=>'contact'));?>">Contact</a></li>
              <li class="dropdown">
                <a href="/" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="/">Action</a></li>
                  <li><a href="/">Another action</a></li>
                  <li><a href="/">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="/">Separated link</a></li>
                  <li><a href="/">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>


        <div class="container">
            <?php echo $this->content; ?>
        </div> 
        


        
  </div>

  
  <div id="footer">
    <div class="container">
      <p class="text-muted credit">2009 - 2013 Tineo .  
              <img src="img/php5-power-micro.png"> 
              <img src="img/zf2-power-micro.png"> 
              <img src="img/80x16_2.gif"></p>
    </div>
  </div>
      <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'tineo'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
