<!DOCTYPE html>
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<meta charset="utf-8" />
<title>Makiblog - Admin Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta content="" name="description" />
<meta content="" name="author" />
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() .'/assets/plugins/pace/pace-theme-flash.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/bootstrap/css/bootstrap.min.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/bootstrap/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() .'/assets/plugins/font-awesome/css/font-awesome.css')
    ->prependStylesheet($this->basePath() .'/assets/css/animate.min.css')

    ->prependStylesheet($this->basePath() .'/assets/css/style.css')
    ->prependStylesheet($this->basePath() .'/assets/css/custom-icon-set.css');
?>

<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    // BEGIN CORE TEMPLATE JS 
    ->prependFile($this->basePath() . '/assets/plugins/jquery-1.8.3.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/assets/plugins/jquery-validation/js/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/assets/js/login.js');
?>

</head>
<body class="error-body no-top">
<div class="container">
  <div class="row">
    <div class="login-container span12">
      <div class="row-fluid column-seperation" style="padding:0 10px">
        <div class="span6 offset1">
          <h2>Sign in to Makiblog</h2>
          <p>Use Facebook, Twitter or your email to sign in.<br>
            <a href="#">Sign up Now!</a> for a webarch account,It's free and always will be..</p>
          <br>
          <div class="row-fluid">
            <button class="btn btn-block btn-info span10" type="button">
            <div class="pull-left"><i class="icon-facebook"></i></div>
            <span class="bold">Login with Facebook</span> </button>
          </div>
          <br>
          <div class="row-fluid">
            <button class="btn btn-block btn-success span10" type="button">
            <div class="pull-left"><i class="icon-twitter"></i></div>
            <span class="bold">Login with Twitter</span></button>
          </div>
        </div>
        <div class="span5"> <br>



<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>







<!--

		 <form id="login-form" class="login-form" action="index.html" method="post">
		 <div class="row-fluid">
		 <div class="control-group span10">
            <label class="control-label">Username</label>
            <div class="controls">
				<div class="input-with-icon  right">                                       
					<i class=""></i>
					<input type="text" name="txtusername" id="txtusername" class="span12">                                 
				</div>
            </div>
          </div>
          </div>
		  <div class="row-fluid">
          <div class="control-group span10">
            <label class="control-label">Password</label>
            <span class="help"></span>
            <div class="controls">
				<div class="input-with-icon  right">                                       
					<i class=""></i>
					<input type="password" name="txtpassword" id="txtpassword" class="span12">                                 
				</div>
            </div>
          </div>
          </div>
		  <div class="row-fluid">
          <div class="control-group  span10">
            <div class="checkbox checkbox check-success"> <a href="#">Trouble login in?</a>&nbsp;&nbsp;
              <input type="checkbox" id="checkbox1" value="1">
              <label for="checkbox1">Keep me reminded </label>
            </div>
          </div>
          </div>
          <div class="row-fluid">
            <div class="span10">
              <button class="btn btn-primary btn-cons pull-right" type="submit">Login</button>
            </div>
          </div>
		  </form>
    -->
        </div>
      </div>
    </div>
  </div>
</div>


</body>
</html>